spring.application.name=DiplomProject


spring.datasource.url=jdbc:sqlserver://localhost:1433;database=course_shop_db;trustServerCertificate=true;
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update

spring.mvc.hiddenmethod.filter.enabled=true
